all:
	#gcc -O3 -msse2 -DHAVE_SSE2 -DSFMT_MEXP=216091 gillespie.c ../SFMT-src-1.4.1/SFMT.c -o x_gcc -I../SFMT-src-1.4.1 
	icc -O3 -msse2 -DHAVE_SSE2 -DSFMT_MEXP=216091 gillespie.c ../SFMT-src-1.4.1/SFMT.c -o x_icc -I../SFMT-src-1.4.1 

